### PR TITLE
Auto-locating user

### PR DESCRIPTION
**Pull request by CarlyRaeJepsenStan**
Added ./utils/auto-locate.js.  Function exported and can be used as autoLocate() - it accepts a callback as an argument, hopefully it works. 
Also, I changed the readme to differentiate this from the original repo - make sure not to merge the readme edits by mistake.

### CODE REVIEW

**Comment by CarlyRaeJepsenStan** [comment]
What's the status on this PR?  Should I make any further changes?

**Comment by jmtellez** [comment]
There are some conflicts, resolve them, and pull new changes. Use arrow functions for `auto-locate` and only commit correct files.

**Comment by CarlyRaeJepsenStan** [comment]
Ok, I'll work on that.

**Comment by jmtellez** [comment]
You are not calling auto-locate anywhere, also just commit the files you are changing, so basically just `./utils/autolocate` and app.js if you are planning to make the call. I can make the call if you'd like

**Comment by CarlyRaeJepsenStan** [comment]
Yeah, I was just going to add ./utils/autolocate because I think some changes were made to app.js.

**Comment by jmtellez** [comment]
if the changes are only on `autolocate.js` just commit that file. It should only be one file changed
I can then call your function on entry file `app.js`

**Comment by CarlyRaeJepsenStan** [comment]
Ok!  I'm going to delete this pull request and open a new one with only one changed file.

**Pull request closed without merging**
